[Scia Reto](https://sciareto.org) mind map
> __version__=`1.1`,showJumps=`true`
---

# 逻辑架构

## 用户（频道）系统

### 用户注册

### 登录

### 用户身份认证

### 频道

#### 管理频道

#### 设置频道

## 视频频道
> leftSide=`true`


### 视频上传

#### 阿里云 VOD

#### RAM 身份

#### 视频上传认证

#### 视频入库

#### 更新视频

### 视频管理

#### 视频详情

#### 视频列表

#### 视频删除

#### 播放记录

### 热门推荐机制

#### 点赞、收藏、转发

## 交互频道
> leftSide=`true`


### 关注频道

### 发布视频列表

### 粉丝与关注系统

#### 频道视频列表

#### 用户视频列表

#### 视频评论

#### 点赞与取消点赞

#### 收藏视频

### 我的

#### 点赞

#### 观看记录

#### 收藏

#### 评论
